
---
- name: install web-server
  hosts: win
  gather_facts: no
  become: no
  tasks:
    - name: Ensure IIS service is stopped
      ansible.windows.win_service:
        name: W3SVC
        state: stopped
